### ISSUE TITLE
AttibuteError on calling train

### ISSUE THREAD

**Issue by prmadhu** [inejc/paragraph-vectors#21]
##### PyTorch and CUDA versions
torch version : 0.1.9_2.
cuda is not installed.

##### Description
I am running the train.py as it is mentioned in the description with the "example.csv" file and the same parameters. I am running into 

> AttributeError: 'module' object has no attribute 'HalfTensor'

##### Additional info (stack trace, etc.)
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from paragraphvec.data import load_dataset, NCEData
  File "/home/prathmesh/paragraph-vectors/paragraphvec/data.py", line 11, in <module>
    from torchtext.data import Field, TabularDataset
  File "/usr/local/lib/python2.7/dist-packages/torchtext/__init__.py", line 1, in <module>
    from . import data
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/__init__.py", line 4, in <module>
    from .field import RawField, Field, ReversibleField, SubwordField
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 61, in <module>
    class Field(RawField):
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 117, in Field
    torch.HalfTensor: float,
AttributeError: 'module' object has no attribute 'HalfTensor'

**Comment by inejc** [comment]
Try with the latest PyTorch version, i.e. `0.3.1`. I was using `0.2.0.post3` when I was developing this.

**Comment by prmadhu** [comment]
Alright, upgrading it to 0.3.1 worked. Thanks.
