### ISSUE TITLE
  File "paragraphvec/train.py", line 8, in <module>     from paragraphvec.data import load_dataset, NCEData ModuleNotFoundError: No module named 'paragraphvec'

### ISSUE THREAD

**Issue by monajalal** [inejc/paragraph-vectors#25]
How should I fix this error?

```
[jalal@goku paragraph-vectors]$ python paragraphvec/train.py start --data_file_name 'data/example.csv' --num_epochs 10 --batch_size 32 --num_noise_words 2 --vec_dim 100 --lr 1e-3
Traceback (most recent call last):
  File "paragraphvec/train.py", line 8, in <module>
    from paragraphvec.data import load_dataset, NCEData
ModuleNotFoundError: No module named 'paragraphvec'
```

```
$ python -V
Python 3.6.4 :: Anaconda custom (64-bit)
```

**Comment by monajalal** [comment]
import sys
Solved this way:
```
from __future__ import absolute_import
sys.path.append("path to paragraph-vectors/paragraphvec")
#from paragraphvec.data import load_dataset, NCEData
from data import load_dataset, NCEData
#from paragraphvec.loss import NegativeSampling
from loss import NegativeSampling
from models import DM, DBOW
#from paragraphvec.models import DM, DBOW
from utils import save_training_state
#from paragraphvec.utils import save_training_state
```

**Comment by Sibasish-Padhy** [comment]
@monajalal if I want to train/convert the paragraphs of some other csv file other than examples.csv how will I import it using your code?
