### ISSUE TITLE
TypeError in data.py - process.start()

### ISSUE THREAD

**Issue by deborshigoswami95** [inejc/paragraph-vectors#28]
##### PyTorch and CUDA versions
pytorch - 0.4.1
CUDA - 9.0

##### Description
I am having an issue with data.py. on line 119, process.start() yields the following error: <br>
TypeError: 'generator' object is not callable. Could you please help?

**Comment by inejc** [comment]
Hey @deborshigoswami95, could you please append the stack trace? Thanks.

**Comment by deborshigoswami95** [comment]
Hi @inejc , Thanks for the quick response. I've copied the trace below. Also, I should mention, I am on a windows system.

#### Stack Trace

Traceback (most recent call last):
  File "train.py", line 216, in <module>
    fire.Fire()
  File "C:\Users\user\Anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\user\Anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\user\Anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 103, in start
    nce_data.start()
  File "C:\Users\user\....\paragraph-vectors\paragraphvec\data.py", line 119, in start
    process.start()
  File "C:\Users\user\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'generator' object is not callable

**Comment by inejc** [comment]
Sorry for the late reply. Would it be possible for you to run this in docker (in a Linux env) to confirm that there is a problem with your Windows installation?

**Comment by deborshigoswami95** [comment]
Hi. Am trying to install docker on windows 10 home. Will let you know after I test the code.

**Comment by nnakshat** [comment]
Hi @deborshigoswami95 , was this issue fixed?
If not, how did you circumvent this problem?

**Comment by shreyansh26** [comment]
Hi, this is still a persistent issue, can somebody who solved this, please provide a solution?

**Comment by inejc** [comment]
What python version are you using on what OS platform?

**Comment by inastasi** [comment]
> What python version are you using on what OS platform?

Hello,
I am facing the same issue.
I am running Python 3.8.5 on Windows 10. Pytorch version 1.5.1.
Thanks!

**Comment by ceyhunemreozturk** [comment]
I got the same error (with same stack trace as @[deborshigoswami95](https://github.com/deborshigoswami95)) on Windows today. 

Are there any updates about the issue? Is this paragraph-vectors repo not compatible with Windows?

**Comment by navidaftabi** [comment]
Hi, I have got the same error. Does this issue be resolved?

I run the code on Google Colab without receiving this error. But, when I try it on my own computer the error occurs.

**Comment by inejc** [comment]
I haven't tested this on Windows unfortunately, if anyone is interested in fixing it a PR would be welcome

**Comment by Eng-sarah90** [comment]
I have tested this project in windows , I am very interested in your field of deep learning by pytorch and Doc2vec
I am running Python 3.10. On Windows 10.
My problem is in data.py
Is it possible to use the dataset file in Pickle format instead of the text file in CSV format?

Thanks!
